lines = []
lines.append("\n\n# ── Aportes de Capital e Participacao Dinamica ────────────────────────────────\n\n")
lines.append("@app.post(\"/imoveis/{imovel_id}/aportes\")\n")
lines.append("def registrar_aporte(imovel_id: int, dados: dict = Body(...)):\n")
lines.append("    from app.db import engine\n")
lines.append("    from sqlalchemy import text\n")
lines.append("    from datetime import date\n")
lines.append("    produtor_id = dados['produtor_id']\n")
lines.append("    valor = float(dados['valor'])\n")
lines.append("    data_aporte = dados.get('data_aporte', date.today().isoformat())\n")
lines.append("    descricao = dados.get('descricao', 'Aporte de capital')\n")
lines.append("    with engine.connect() as conn:\n")
lines.append("        conn.execute(text('INSERT INTO aportes_capital (imovel_id, produtor_id, valor, data_aporte, descricao) VALUES (:iid, :pid, :valor, :data, :desc)'),\n")
lines.append("            {'iid': imovel_id, 'pid': produtor_id, 'valor': valor, 'data': data_aporte, 'desc': descricao})\n")
lines.append("        conn.execute(text('UPDATE participacoes_imovel SET capital_aportado = COALESCE(capital_aportado, 0) + :valor WHERE imovel_id = :iid AND produtor_id = :pid AND vigencia_fim IS NULL'),\n")
lines.append("            {'iid': imovel_id, 'pid': produtor_id, 'valor': valor})\n")
lines.append("        total_row = conn.execute(text('SELECT COALESCE(SUM(capital_aportado), 0) FROM participacoes_imovel WHERE imovel_id=:iid AND vigencia_fim IS NULL'), {'iid': imovel_id}).fetchone()\n")
lines.append("        total = float(total_row[0]) if total_row else 0\n")
lines.append("        if total > 0:\n")
lines.append("            socios = conn.execute(text('SELECT id, produtor_id, capital_aportado, nome_participante FROM participacoes_imovel WHERE imovel_id=:iid AND vigencia_fim IS NULL'), {'iid': imovel_id}).fetchall()\n")
lines.append("            for s in socios:\n")
lines.append("                novo_perc = round(float(s[2] or 0) / total * 100, 4)\n")
lines.append("                conn.execute(text('UPDATE participacoes_imovel SET vigencia_fim = :data WHERE id = :id'), {'id': s[0], 'data': data_aporte})\n")
lines.append("                conn.execute(text('INSERT INTO participacoes_imovel (imovel_id, produtor_id, percentual, nome_participante, vigencia_inicio, capital_aportado) VALUES (:iid, :pid, :perc, :nome, :data, :cap)'),\n")
lines.append("                    {'iid': imovel_id, 'pid': s[1], 'perc': novo_perc, 'nome': s[3], 'data': data_aporte, 'cap': float(s[2] or 0)})\n")
lines.append("        conn.commit()\n")
lines.append("        rows = conn.execute(text('SELECT p.produtor_id, pr.nome, p.percentual, p.capital_aportado, p.vigencia_inicio FROM participacoes_imovel p JOIN produtores pr ON pr.id = p.produtor_id WHERE p.imovel_id = :iid AND p.vigencia_fim IS NULL ORDER BY p.percentual DESC'), {'iid': imovel_id}).fetchall()\n")
lines.append("        total_cap = sum(float(r[3] or 0) for r in rows)\n")
lines.append("        return {'imovel_id': imovel_id, 'data_aporte': data_aporte, 'total_capital': total_cap,\n")
lines.append("                'participacoes': [{'produtor_id': r[0], 'nome': r[1], 'percentual': float(r[2]), 'capital_aportado': float(r[3] or 0), 'vigencia_inicio': str(r[4])} for r in rows]}\n")
lines.append("\n\n")
lines.append("@app.get(\"/imoveis/{imovel_id}/aportes\")\n")
lines.append("def listar_aportes(imovel_id: int):\n")
lines.append("    from app.db import engine\n")
lines.append("    from sqlalchemy import text\n")
lines.append("    with engine.connect() as conn:\n")
lines.append("        rows = conn.execute(text('SELECT a.id, a.produtor_id, pr.nome, a.valor, a.data_aporte, a.descricao FROM aportes_capital a JOIN produtores pr ON pr.id = a.produtor_id WHERE a.imovel_id = :iid ORDER BY a.data_aporte DESC'), {'iid': imovel_id}).fetchall()\n")
lines.append("        tots = conn.execute(text('SELECT produtor_id, SUM(valor) as total FROM aportes_capital WHERE imovel_id = :iid GROUP BY produtor_id'), {'iid': imovel_id}).fetchall()\n")
lines.append("        total_geral = sum(float(r[1]) for r in tots)\n")
lines.append("        return {'total_capital': total_geral,\n")
lines.append("                'por_socio': [{'produtor_id': r[0], 'total': float(r[1]), 'percentual': round(float(r[1])/total_geral*100, 2) if total_geral > 0 else 0} for r in tots],\n")
lines.append("                'historico': [{'id': r[0], 'produtor_id': r[1], 'nome': r[2], 'valor': float(r[3]), 'data_aporte': str(r[4]), 'descricao': r[5]} for r in rows]}\n")

with open("app/main.py", "a", encoding="utf-8") as f:
    f.writelines(lines)
print("OK - endpoints aportes adicionados!")
