import psycopg2
conn = psycopg2.connect("postgresql://postgres:tkyfcRsbrZuuHoThKgjuTiZWYVXOTdOX@gondola.proxy.rlwy.net:53900/railway")
cur = conn.cursor()
cur.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name='participacoes_imovel' ORDER BY ordinal_position")
print("PARTICIPACOES_IMOVEL:", cur.fetchall())
cur.execute("SELECT * FROM participacoes_imovel WHERE imovel_id=1 ORDER BY vigencia_inicio")
print("DADOS:", cur.fetchall())
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='lancamentos' ORDER BY ordinal_position")
print("LANCAMENTOS cols:", [r[0] for r in cur.fetchall()])
conn.close()
