import psycopg2
conn = psycopg2.connect('postgresql://postgres:tkyfcRsbrZuuHoThKgjuTiZWYVXOTdOX@gondola.proxy.rlwy.net:53900/railway')
cur = conn.cursor()
cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name")
print('Tabelas:', [r[0] for r in cur.fetchall()])
cur.execute("SELECT column_name, data_type FROM information_schema.columns WHERE table_name='produtores' ORDER BY ordinal_position")
print()
print('Colunas produtores:')
for r in cur.fetchall(): print(f'  {r[0]}: {r[1]}')
conn.close()
