# -*- coding: utf-8 -*-
# Estrutura: (codigo, descricao, tipo, dedutivel, observacao)

PLANO_DETALHADO = [
    ("1", "RECEITAS", "receita", "Não", ""),
    ("1.1", "Receita da Produção Agrícola", "receita", "Não", ""),
    ("1.1.1", "Venda de grãos", "receita", "Não", ""),
    ("1.1.2", "Venda de frutas", "receita", "Não", ""),
    ("1.1.3", "Venda de hortaliças", "receita", "Não", ""),
    ("1.1.4", "Venda de raízes e tubérculos", "receita", "Não", ""),
    ("1.1.5", "Venda de culturas permanentes", "receita", "Não", ""),
    ("1.1.6", "Venda de subprodutos agrícolas", "receita", "Não", ""),
    ("1.2", "Receita da Produção Pecuária", "receita", "Não", ""),
    ("1.2.1", "Bovinocultura de corte", "receita", "Não", ""),
    ("1.2.2", "Bovinocultura de leite", "receita", "Não", ""),
    ("1.2.3", "Ovinocultura de corte", "receita", "Não", ""),
    ("1.2.4", "Ovinocultura de leite", "receita", "Não", ""),
    ("1.2.5", "Caprinocultura de corte", "receita", "Não", ""),
    ("1.2.6", "Caprinocultura de leite", "receita", "Não", ""),
    ("1.2.7", "Suinocultura", "receita", "Não", ""),
    ("1.2.8", "Avicultura", "receita", "Não", ""),
    ("1.2.9", "Piscicultura", "receita", "Não", ""),
    ("1.3", "Produtos pecuários", "receita", "Não", ""),
    ("1.3.1", "Venda de leite", "receita", "Não", "Antes gravado ad-hoc como 4.1.2 nas subcontas"),
    ("1.3.2", "Venda de ovos", "receita", "Não", ""),
    ("1.3.3", "Venda de mel", "receita", "Não", ""),
    ("1.3.4", "Venda de peixes", "receita", "Não", ""),
    ("1.3.5", "Venda de lã", "receita", "Não", ""),
    ("1.3.6", "Venda de esterco e subprodutos", "receita", "Não", ""),
    ("1.4", "Serviços e outras receitas rurais", "receita", "Não", ""),
    ("1.4.1", "Aluguel de máquinas e equipamentos", "receita", "Não", ""),
    ("1.4.2", "Prestação de serviços agrícolas", "receita", "Não", "Cobre o código solto 1.2 usado pela IA (sem existir no plano oficial)"),
    ("1.4.3", "Arrendamento rural recebido", "receita", "Não", ""),
    ("1.4.4", "Parcerias rurais", "receita", "Não", ""),
    ("1.4.5", "Contratos e recibos avulsos", "receita", "Não", "Novo — cobre módulo de Recibo e Contratos Rurais (assinatura eletrônica)"),

    ("2", "DESPESAS OPERACIONAIS", "despesa", "Sim", ""),
    ("2.1", "Produção Agrícola", "despesa", "Sim", ""),
    ("2.1.1", "Sementes", "despesa", "Sim", ""),
    ("2.1.2", "Mudas", "despesa", "Sim", ""),
    ("2.1.3", "Fertilizantes", "despesa", "Sim", ""),
    ("2.1.4", "Corretivos de solo", "despesa", "Sim", ""),
    ("2.1.5", "Defensivos agrícolas", "despesa", "Sim", ""),
    ("2.1.6", "Irrigação e materiais agrícolas", "despesa", "Sim", ""),
    ("2.1.7", "Mão de obra agrícola", "despesa", "Sim", ""),
    ("2.1.8", "Colheita e pós-colheita", "despesa", "Sim", ""),

    ("2.2", "Produção Pecuária", "despesa", "Sim", "Substitui a conta genérica 3.1.3 (Despesas com pecuária)"),
    ("2.2.1", "Alimentação animal", "despesa", "Sim", ""),
    ("2.2.1.1", "Alimentação — Bovinocultura de corte", "despesa", "Sim", ""),
    ("2.2.1.2", "Alimentação — Bovinocultura de leite", "despesa", "Sim", "Equivalente ao antigo 3.1.3.1 (ração)"),
    ("2.2.1.2.1", "Ração/concentrado de lactação", "despesa", "Sim", "Equivalente exato ao antigo 3.1.3.1.1, usado no cálculo de IOFC"),
    ("2.2.1.2.2", "Volumoso e silagem", "despesa", "Sim", ""),
    ("2.2.1.2.3", "Suplemento mineral", "despesa", "Sim", ""),
    ("2.2.1.3", "Alimentação — Ovinocultura", "despesa", "Sim", ""),
    ("2.2.1.4", "Alimentação — Caprinocultura", "despesa", "Sim", ""),
    ("2.2.1.5", "Alimentação — Suinocultura", "despesa", "Sim", ""),
    ("2.2.1.6", "Alimentação — Avicultura", "despesa", "Sim", ""),
    ("2.2.1.7", "Alimentação — Piscicultura (ração)", "despesa", "Sim", ""),

    ("2.2.2", "Medicamentos e vacinas", "despesa", "Sim", ""),
    ("2.2.2.1", "Medicamentos — Bovinocultura de corte", "despesa", "Sim", ""),
    ("2.2.2.2", "Medicamentos — Bovinocultura de leite", "despesa", "Sim", "Equivalente ao antigo 3.1.3.2 (veterinário)"),
    ("2.2.2.3", "Medicamentos — Ovinocultura", "despesa", "Sim", ""),
    ("2.2.2.4", "Medicamentos — Caprinocultura", "despesa", "Sim", ""),
    ("2.2.2.5", "Medicamentos — Suinocultura", "despesa", "Sim", ""),
    ("2.2.2.6", "Medicamentos — Avicultura", "despesa", "Sim", ""),
    ("2.2.2.7", "Medicamentos — Piscicultura", "despesa", "Sim", ""),

    ("2.2.3", "Reprodução", "despesa", "Sim", ""),
    ("2.2.4", "Manejo e sanidade", "despesa", "Sim", ""),
    ("2.2.4.1", "Higiene de ordenha", "despesa", "Sim", "Equivalente ao antigo 3.1.3.3"),
    ("2.2.4.2", "Tosquia", "despesa", "Sim", ""),
    ("2.2.4.3", "Vacinação e manejo geral", "despesa", "Sim", ""),

    ("2.2.5", "Serviços veterinários", "despesa", "Sim", ""),
    ("2.2.6", "Mão de obra pecuária", "despesa", "Sim", ""),
    ("2.2.7", "Energia e água da produção", "despesa", "Sim", "Recebe o antigo 3.1.6 quando o gasto for da atividade pecuária"),
    ("2.2.8", "Manutenção de instalações pecuárias", "despesa", "Sim", ""),

    ("2.3", "Combustíveis e lubrificantes", "despesa", "Sim", ""),
    ("2.3.1", "Diesel", "despesa", "Sim", "Recebe o antigo 3.1.2 quando o item for diesel"),
    ("2.3.2", "Gasolina e etanol", "despesa", "Sim", ""),
    ("2.3.3", "Lubrificantes e graxas", "despesa", "Sim", ""),

    ("2.4", "Manutenção", "despesa", "Sim", ""),
    ("2.4.1", "Máquinas e equipamentos", "despesa", "Sim", "Recebe o antigo 3.1.5"),
    ("2.4.2", "Veículos", "despesa", "Sim", ""),
    ("2.4.3", "Cercas, currais e apriscos", "despesa", "Sim", ""),
    ("2.4.4", "Galpões e instalações", "despesa", "Sim", ""),
    ("2.4.5", "Sistemas de irrigação e tanques", "despesa", "Sim", ""),

    ("2.5", "Mão de obra e serviços", "despesa", "Sim", ""),
    ("2.5.1", "Salários", "despesa", "Sim", "Recebe parte do antigo 3.1.4"),
    ("2.5.2", "Encargos trabalhistas", "despesa", "Sim", "Recebe parte do antigo 3.1.4"),
    ("2.5.3", "Diárias e serviços de terceiros", "despesa", "Sim", ""),

    ("2.6", "Despesas administrativas e gerais", "despesa", "Sim", ""),
    ("2.6.1", "Contabilidade e consultorias", "despesa", "Sim", ""),
    ("2.6.2", "Telefonia e internet", "despesa", "Sim", ""),
    ("2.6.3", "Seguros", "despesa", "Sim", ""),
    ("2.6.4", "Taxas e despesas bancárias", "despesa", "Sim", ""),
    ("2.6.5", "Outras despesas não classificadas", "despesa", "Sim", "Recebe o antigo 3.1.99 e o código solto 3.9 usado pela IA"),
    ("2.6.6", "Arrendamento e parceria pagos", "despesa", "Sim", "NOVO — não existia conta de despesa equivalente; o antigo 3.1.7 ficava sem contrapartida clara no plano proposto original"),

    ("3", "INVESTIMENTOS E ATIVO IMOBILIZADO", "investimento", "Não", ""),
    ("3.1", "Máquinas e equipamentos", "investimento", "Não", "Recebe o antigo 5.1"),
    ("3.2", "Veículos", "investimento", "Não", ""),
    ("3.3", "Instalações e benfeitorias", "investimento", "Não", "Recebe o antigo 5.2 (obras e benfeitorias)"),
    ("3.3.1", "Currais", "investimento", "Não", ""),
    ("3.3.2", "Apriscos", "investimento", "Não", ""),
    ("3.3.3", "Galpões", "investimento", "Não", ""),
    ("3.3.4", "Cercas", "investimento", "Não", ""),
    ("3.3.5", "Tanques de piscicultura", "investimento", "Não", ""),
    ("3.4", "Formação de culturas permanentes", "investimento", "Não", ""),
    ("3.5", "Formação e aquisição de rebanho", "investimento", "Não", "Recebe o antigo 5.3"),
    ("3.5.1", "Aquisição de matrizes", "investimento", "Não", ""),
    ("3.5.2", "Aquisição de reprodutores", "investimento", "Não", ""),
    ("3.5.3", "Animais para formação de plantel", "investimento", "Não", ""),

    ("4", "ESTOQUES", "estoque", "Não", "Prefixo 4.x ficava conflitado com receitas ad-hoc (4.1.1 / 4.1.2) — ver aba De-Para"),
    ("4.1", "Estoque de insumos agrícolas", "estoque", "Não", ""),
    ("4.2", "Estoque de insumos pecuários", "estoque", "Não", ""),
    ("4.3", "Estoque de medicamentos e vacinas", "estoque", "Não", ""),
    ("4.4", "Estoque de rações e alimentos", "estoque", "Não", ""),
    ("4.5", "Estoque de sementes e mudas", "estoque", "Não", ""),
    ("4.6", "Estoque de produtos em produção", "estoque", "Não", ""),
    ("4.7", "Estoque de animais para venda", "estoque", "Não", ""),
]

# codigo_atual, descricao_origem, tipo_atual, situacao, codigo_novo, acao_recomendada
DE_PARA = [
    ("1.1", "Receita da atividade rural (plano_contas oficial)", "receita", "Genérico demais — nunca deveria ser destino final de lançamento", "1.1 a 1.4 (por atividade)", "Reclassificar lançamentos existentes por atividade real antes de aposentar o código"),
    ("1.1.1", "Venda de produtos agrícolas (plano_contas oficial)", "receita", "OK, mas raso", "1.1.1 a 1.1.6", "Detalhar por tipo de produto quando souber qual"),
    ("1.1.2", "Venda de produtos pecuários (plano_contas oficial)", "receita", "OK, mas raso", "1.2.1 a 1.2.9 / 1.3.x", "Detalhar por espécie/produto"),
    ("1.1.3", "Receita de arrendamento rural (plano_contas oficial)", "receita", "OK", "1.4.3", "Mapeamento direto"),
    ("3.1.1", "Custeio agrícola (plano_contas oficial)", "despesa", "Genérico demais", "2.1.1 a 2.1.8", "Detalhar por insumo quando possível"),
    ("3.1.2", "Combustíveis e lubrificantes (plano_contas oficial)", "despesa", "OK, mas raso", "2.3.1 a 2.3.3", "Detalhar por tipo de combustível"),
    ("3.1.3", "Despesas com pecuária (plano_contas oficial)", "despesa", "Conflita com granularidade real (ver 3.1.3.1 abaixo)", "2.2.1 a 2.2.8", "Aposentar em favor dos códigos granulares já usados em subcontas"),
    ("3.1.3.1", "Ração (subcontas.codigo_conta, bovino leite)", "despesa", "Já granular e em uso ativo — não mexer sem migração", "2.2.1.2", "Migrar preservando histórico (UPDATE em lote)"),
    ("3.1.3.1.1", "Ração/concentrado de lactação (subcontas.codigo_conta)", "despesa", "Em uso no cálculo de IOFC — crítico", "2.2.1.2.1", "Migrar com cuidado extra; usado no endpoint /bovino/leiteiro/iofc"),
    ("3.1.3.2", "Veterinário (subcontas.codigo_conta)", "despesa", "Em uso", "2.2.2.2", "Migrar em lote"),
    ("3.1.3.3", "Higiene de ordenha (subcontas.codigo_conta)", "despesa", "Em uso", "2.2.4.1", "Migrar em lote"),
    ("3.1.4", "Mão de obra e encargos (plano_contas oficial)", "despesa", "Genérico", "2.5.1 e 2.5.2", "Separar salário de encargos"),
    ("3.1.5", "Manutenção de máquinas (plano_contas oficial)", "despesa", "OK", "2.4.1", "Mapeamento direto"),
    ("3.1.6", "Energia elétrica rural (plano_contas oficial)", "despesa", "OK", "2.2.7 ou geral", "Decidir se é da pecuária ou geral da propriedade"),
    ("3.1.7", "Arrendamentos pagos (plano_contas oficial)", "despesa", "Sem conta equivalente no plano novo original", "2.6.6 (NOVA)", "Conta criada nesta revisão"),
    ("3.1.8.1", "Descrição não confirmada (subconta em uso, achado na auditoria de 24/07)", "despesa", "Pendente de confirmação ao vivo no banco", "A definir", "Rodar SELECT nome, tipo FROM subcontas WHERE codigo_conta = '3.1.8.1'"),
    ("3.1.99", "Outros (mapeamento da IA)", "despesa", "Código solto, não existe no plano oficial", "2.6.5", "Mapeamento direto"),
    ("1.2", "Serviço prestado (mapeamento da IA)", "receita", "Código solto, não existe no plano oficial", "1.4.2", "Mapeamento direto"),
    ("3.9", "Outros (mapeamento da IA)", "despesa", "Código solto, não existe no plano oficial", "2.6.5", "Mapeamento direto"),
    ("4.1.1", "Descrição não confirmada (subconta em uso, ~15 lançamentos, tipo RECEITA)", "receita", "Pendente de confirmação — colide com o novo prefixo 4.x de Estoques", "A definir dentro de 1.3.x ou 1.4.x", "Rodar SELECT nome FROM subcontas WHERE codigo_conta = '4.1.1'"),
    ("4.1.2", "Venda de Leite (subcontas, UUID 1d3e0f2c-9bfb-49ab-a603-1c42fc434a75)", "receita", "Colide com o novo prefixo 4.x de Estoques", "1.3.1", "Migrar; é a mesma conta, só muda o código"),
    ("5.1", "Aquisição de máquinas (plano_contas oficial)", "investimento", "OK", "3.1", "Mapeamento direto"),
    ("5.2", "Obras e benfeitorias (plano_contas oficial)", "investimento", "OK, mas raso", "3.3 (detalhar em 3.3.1-3.3.5 quando souber o tipo)", "Detalhar por tipo de benfeitoria"),
    ("5.3", "Aquisição de animais (plano_contas oficial)", "investimento", "OK, mas raso", "3.5.3", "Detalhar entre matriz/reprodutor/plantel quando possível"),
]
